create table superplayermud
(
	id			mediumint,
	hp			mediumint,
	maxhp			mediumint,
	mana			mediumint,
	maxmana			mediumint,
	move			mediumint,
	maxmove			mediumint,
	intelligence		mediumint,
	wisdom			mediumint,
	charisma		mediumint,
	strength		mediumint,
	dexterity		mediumint,
	max_intelligence	mediumint,
	max_wisdom		mediumint,
	max_charisma		mediumint,
	max_strength		mediumint,
	max_dexterity		mediumint,
	hitroll			mediumint,
	damroll			mediumint,
	magic_res		mediumint,
	cast_level		mediumint,
	mage			mediumint,
	cleric			mediumint,
	thief			mediumint,
	warrior			mediumint,
	mod			DATETIME
)
